apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-deployment
  namespace: assignment
  labels:
    app: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
      - name: cicd
        image: zainulsyed/my-project:1.0
        ports:
        - containerPort: 80


