apiVersion: v1
kind: Service
metadata:
  name: cicd-service
  namespace: assignment
spec:
  type: NodePort
  selector:
    app: cicd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
